name: lotto_app
description: "A Lottery Result App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  animated_flip_counter: ^0.3.4
  carousel_slider: ^5.0.0
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^14.6.3
  http: ^1.4.0
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.2
  scratcher: ^2.5.0
  shared_preferences: ^2.5.3
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2C2C2C"
  adaptive_icon_foreground: "assets/icons/logo.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
