name: lotto_app
description: "A Lottery Result App"
publish_to: "none"

version: 1.5.04+58

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  confetti: ^0.8.0
  connectivity_plus: ^6.1.0
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  firebase_analytics: ^12.0.1
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.4.1
  fluttertoast: ^8.2.12
  go_router: ^16.2.1
  google_mobile_ads: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  image_picker: ^1.1.2
  in_app_update: ^4.2.3
  mobile_scanner: ^7.0.1
  package_info_plus: ^8.3.0
  path_provider: ^2.1.4
  pdf: ^3.11.3
  permission_handler: ^12.0.1
  scratcher: ^2.5.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  typewritertext: ^3.0.9
  url_launcher: ^6.3.1
  youtube_player_iframe: ^5.2.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/new_small_logo.png" # Use your foreground image as the default/legacy icon
  adaptive_icon_foreground: "assets/icons/new_foregraund.png" # Updated to your new path
  adaptive_icon_background: "#FFFFFF" # Updated to your new path
  # remove_alpha_ios: true # Not needed if ios: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/fonts/
fonts:
  - family: NotoSans
    fonts:
      - asset: assets/fonts/NotoSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/NotoSans_Condensed-Bold.ttf
        weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
# flutter_native_splash:
#   color: "#ffffff"
#   image: assets/icons/logo_foreground.png
#   color_dark: "#000000"
#   image_dark: assets/icons/logo_foreground.png
#   android: true
#   ios: false
#   android_12:
#     image: assets/icons/new_small_logo115.png
#     color: "#FFFFFF"


